[package]
name = "openai-rs"
version = "0.1.0"
edition = "2021"
authors = [
    "Kamil Litman <kamil@neferdata.com>",
    "Dario Lencina <dario@neferdata.com>",
]
description = "OpenAI Framework for Rust"
license = "MIT or Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
